# Generated by Codex for Stage 3 indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["date"],
                name="session_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["workout_type", "date"],
                name="session_type_date_idx",
            ),
        ),
    ]
